version: '3'
services:
    web:
        restart: always
        build: .
        volumes:
            - ./:/var/www/
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: ms-sanctum-db
        ports:
            - "3306:3306"
        volumes:
            - 'db-sanctum:/var/lib/mysql/'

    nginx:
        build: ./.docker/nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
        depends_on:
            - web
volumes:
    db-sanctum:
